[models]
all = [
    "Qwen/Qwen3.5-397B-A17B-TEE",
    "zai-org/GLM-5-TEE",
    "moonshotai/Kimi-K2.5-TEE",
    "MiniMaxAI/MiniMax-M2.5-TEE",
]

[aliases]
"Qwen/Qwen3.5-397B-A17B-TEE" = "qwen3.5-plus"
"zai-org/GLM-5-TEE" = "glm-5"
"moonshotai/Kimi-K2.5-TEE" = "kimi-k2.5"
"MiniMaxAI/MiniMax-M2.5-TEE" = "MiniMax-M2.5"
