---
all:
  children:
    shared_servers:
      hosts:
        private_server:
          ansible_host: private
          ansible_user: dima
          server_scope: private
          hosting_provider: netcup
