---
- name: Update Coach service
  hosts: all
  become: true

  tasks:

  - name: Update Coach file
    template:
      src: ../templates/Coach.j2
      dest: "/etc/systemd/system/coach.service"
      owner: root
      group: root
    notify:
      - Reload systemd
      - Reload Coach

  handlers:
  - name: Reload systemd
    systemd:
      daemon_reload: yes
  - name: Reload Coach
    systemd:
      name: coach
      enabled: true
      state: restarted
