---
- name: Install and Upgrade Caddy
  hosts: all
  become: true

  vars:
    caddy_version: "latest"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        pkg:
          - debian-keyring
          - debian-archive-keyring
          - apt-transport-https
        state: present

    - name: Add Caddy GPG key
      apt_key:
        url: https://dl.cloudsmith.io/public/caddy/stable/gpg.key
        state: present

    - name: Add Caddy repository
      apt_repository:
        repo: "deb https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main"

    - name: Install or upgrade Caddy
      apt:
        name: caddy
        state: latest

    - name: Ensure Caddy service is enabled and started
      systemd:
        name: caddy
        state: started
        enabled: yes
